### PR TITLE
Replaced non-standard inquire by refactoring

### LINKED ISSUE #48: accessom2_restart.nml not being written to restart dir
The latest libaccessom2 (d7c3c2835017) writes `accessom2_restart.nml` to `outputnnn` but not to `restartnnn`, causing an abort with `Error in accessom2_deinit: atm and ice models are out of sync.` at the end of the subsequent run.
(Also, `accessom2_restart.nml` is written to `outputnnn` as a regular file, rather than a symlink to `restartnnn-1/accessom2_restart.nml`).

4198e150 worked fine, so the problem was introduced somewhere in these changes : https://github.com/COSIMA/libaccessom2/compare/4198e150...d7c3c2835017

I suspect this change is the culprit: https://github.com/COSIMA/libaccessom2/blob/d7c3c2835017ad64cd07b5126b129b23f028478a/libcouple/src/accessom2.F90#L837
which had been
https://github.com/COSIMA/libaccessom2/blob/4198e1507a39eb4b051b3751a7e13634c7804516/libcouple/src/accessom2.F90#L837

I'll revert this line and see if it fixes this problem

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Closes #48

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
Happy to merge this @aekiss?

Not sure why the CI isn't showing automatically, but this does pass the compilation test

https://travis-ci.org/github/COSIMA/libaccessom2/builds/696291045

**Review by russfiedler — COMMENTED** [review]
Brute force. I like it.

**Comment by aidanheerdegen** [comment]
I blame `python` and it's ask for forgiveness rather than permission approach. Arguably this is better code, as it will also pick up issues with writing to the `RESTART` directory.

As @russfiedler has reviewed and given the thumbs up, and the automated jenkins testing is still borked,  will merge. Can you then give it a burl to check it fixes the bug I introduced @aekiss?

**Comment by aekiss** [comment]
thanks @aidanheerdegen, this is working

**Comment by aidanheerdegen** [comment]
Thanks @aekiss. The least I could do seeing as I broke it. I'll push a new tag to trigger a release, which is how access-om2 uses libaccessom2.

**Pull request merged**
