### PR TITLE
revert to directory existence check for restart

### LINKED ISSUE #48: accessom2_restart.nml not being written to restart dir
The latest libaccessom2 (d7c3c2835017) writes `accessom2_restart.nml` to `outputnnn` but not to `restartnnn`, causing an abort with `Error in accessom2_deinit: atm and ice models are out of sync.` at the end of the subsequent run.
(Also, `accessom2_restart.nml` is written to `outputnnn` as a regular file, rather than a symlink to `restartnnn-1/accessom2_restart.nml`).

4198e150 worked fine, so the problem was introduced somewhere in these changes : https://github.com/COSIMA/libaccessom2/compare/4198e150...d7c3c2835017

I suspect this change is the culprit: https://github.com/COSIMA/libaccessom2/blob/d7c3c2835017ad64cd07b5126b129b23f028478a/libcouple/src/accessom2.F90#L837
which had been
https://github.com/COSIMA/libaccessom2/blob/4198e1507a39eb4b051b3751a7e13634c7804516/libcouple/src/accessom2.F90#L837

I'll revert this line and see if it fixes this problem

### PR DESCRIPTION
**Pull request by aekiss**
this fixes https://github.com/COSIMA/libaccessom2/issues/48

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
I'd rather make a PR that works for both Intel and gfortran. This will break the CI

**Comment by aekiss** [comment]
gah, oops sorry @aidanheerdegen

**Comment by aidanheerdegen** [comment]
No worries. I'll do another PR.

**Comment by aekiss** [comment]
I am starting a long 0.1deg IAF experiment and was wanting a config in master that worked... I guess the CI can be sorted out in a branch?

**Comment by aidanheerdegen** [comment]
Sure. Once you've checked out the code though, it shouldn't matter if the repo is changed.

**Comment by russfiedler** [comment]
Since only `yatm` inquires about the directory you could probably do something like `execute_command_line('mkdir -p '// `trim(self%config_dir)//'/RESTART',...)` checking the exit status and then proceed.

Otherwise, calling some C seems like the best option. See here (not the accepted answer).

https://stackoverflow.com/questions/9522933/test-whether-a-directory-exists-or-not

**Pull request merged**
